### ISSUE TITLE
Implementar validação de domínio antes de enviar requisição

### ISSUE THREAD

**Issue by gpedro** [ftonato/registrobr#5]
```
O nome escolhido deve respeitar as seguintes regras sintáticas:

Tamanho mínimo de 2 e máximo de 26 caracteres, não incluindo a categoria. Por exemplo: no domínio xxxx.com.br, esta limitação se refere ao xxxx;
Caracteres válidos são letras de "a" a "z", números de "0" a "9", o hífen, e os seguintes caracteres acentuados: à, á, â, ã, é, ê, í, ó, ô, õ, ú, ü, ç
Não conter somente números;
Não iniciar ou terminar por hífen.
```

Fonte: http://registro.br//dominio/regras.html

**Comment by ftonato** [comment]
@gpedro estava pensando, será que usar _regex_ é uma solução plausível?

**Comment by gpedro** [comment]
@ftonato é como dizem:

> regex resolve um problema e cria mais três.

dá pra resolver com regex:
- Não conter somente números;
- Não iniciar ou terminar por hífen.

dá pra resolver sem regex:
- Tamanho mínimo de 2 e máximo de 26 caracteres, não incluindo a categoria. Por exemplo: no domínio xxxx.com.br, esta limitação se refere ao xxxx;
- Caracteres válidos são letras de "a" a "z", números de "0" a "9", o hífen, e os seguintes caracteres acentuados: à, á, â, ã, é, ê, í, ó, ô, õ, ú, ü, ç
  Não conter somente números;

**Comment by ftonato** [comment]
@gpedro foi o que  pensei hahaha

Como dizem por aí, é hora de _meter a mãos a massa_.

``` javascript
function isNumeric(str) {
  return !isNaN(parseFloat(str)) && isFinite(str);
}

function getLastCharacter(str) {
  return str.slice(-1);
}

function getFirstCharacter(str) {
  return str.charAt(0);
}

function hasTrailingOrLeadingHyphen(str) {
  if (getFirstCharacter(str) == '-' || getLastCharacter(str) == '-') {
    return true;
  }
  return false;
}

function validateDomain(domainName) {
  // Não conter somente números
  if (isNumeric(domainName)) {
    return false;
  }

  // Não iniciar ou terminar por hífen
  if (hasTrailingOrLeadingHyphen(domainName)) {
    return false;
  }

  /* Falta implementar
  ☻ Tamanho mínimo de 2 e máximo de 26 caracteres, não incluindo a categoria. Por exemplo: no domínio xxxx.com.br, esta limitação se refere ao xxxx;
  ☻ Caracteres válidos são letras de "a" a "z", números de "0" a "9", o hífen, e os seguintes caracteres acentuados: à, á, â, ã, é, ê, í, ó, ô, õ, ú, ü, ç Não conter somente números;
  */
}
```

Ainda falta as duas últimas validações...

**Comment by dhyegocalota** [comment]
Imagino que eu validar um hostname, devemos levar em conta os seguintes itens:

```
- TLDs permitidos
- Caracteres permitidos
- Tamanho do hostname
```

Atualmente, utilizo uma lib chamada [validates_hostname](https://github.com/KimNorgaard/validates_hostname/blob/master/lib/validates_hostname.rb) que faz esta validação de uma forma muito bem feita, porém, em Ruby.

**Comment by gpedro** [comment]
dá pra utiliza a lib nativa [`url`](https://nodejs.org/api/url.html) pra validar

**Comment by dhyegocalota** [comment]
``` javascript
import url from 'url';

const isValidHostname = (urlString) => !!url.parse(urlString).hostname.length;

console.log(isValidHostname('https://github.com')) // true
console.log(isValidHostname('huehue')) // false
```

**Comment by ftonato** [comment]
@dhyegofernando @gpedro 

Talvez até seja possível utilizar a lib, mas alguns erros precisam ser resolvidos, exemplo:

``` javascript
console.log(isValidHostname('http://-ftonato-.com.br')) // true
console.log(isValidHostname('http://010203')) // true
```

**Comment by felipefschwade** [comment]
E criar uma função que faz uma requisição pra validar também se o dominio está respondendo ou não? 
Não seria uma boa?

**Comment by ftonato** [comment]
@felipefschwade penso que uma requisição extra seja desnecessário, certamente funções no arquivo cli.js sejam um tanto mais rápidas.

Veja a solução que o @gpedro está desenvolvendo [aqui](https://github.com/gpedro/registrobr/blob/feat/validation/cli.js), ela me parece bem mais plausível.

**Comment by gpedro** [comment]
terminei minha implementação, se possível deem um review nela. >> #6
