### ISSUE TITLE
Erro ao consultar dominio

### ISSUE THREAD

**Issue by leonardoelias** [ftonato/registrobr#7]
~ » registrobr ft.com.br                                                                                       
Alguma coisa de errado não está certo.
SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at /usr/local/lib/node_modules/registrobr/node_modules/node-fetch/lib/body.js:48:15
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by ftonato** [comment]
Fala @leonardoelias, beleza?

Obrigado por reportar, o erro está acontecendo devido a uma mudança na _URL_ de verificação de disponibilidade de domínios...

O problema foi corrigido na última versão publicada no [npmjs - registrobr](https://www.npmjs.com/package/registrobr).

Valeu :sunglasses:
